"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

interface BatchResult {
  questionSetId: string;
  questionCount: number;
  loadVia: "sheet" | "json";
  sheetUrl?: string;
  taskOutputUrl?: string;
  success: boolean;
  error?: string;
  autoFixedDuplicateQuestionIds: number;
  autoGeneratedMissingQuestionIds: number;
}

interface LoadResult {
  success: boolean;
  batches: BatchResult[];
  questionCount: number;
  error?: string;
}

interface LoadToBetaProps {
  problemId: string;
  /** Seeds the sheet name and question set title. */
  defaultTitle?: string;
}

const FIELDS = [
  { key: "sheetName", label: "Sheet name", hint: "Name of the copied loading sheet" },
  { key: "title", label: "QuestionSet title (B2)", hint: "" },
  { key: "childOrder", label: "Child order (G3)", hint: "" },
  { key: "parentResource", label: "Parent resource (H3)", hint: "" },
  { key: "autoUnlock", label: "Auto unlock (I2)", hint: "" },
  { key: "durationInSec", label: "Duration (optional)", hint: "Seconds or MM:SS" },
] as const;

type FieldKey = (typeof FIELDS)[number]["key"];

export function LoadToBeta({ problemId, defaultTitle = "" }: LoadToBetaProps) {
  const [open, setOpen] = useState(false);
  const [configured, setConfigured] = useState<boolean | null>(null);
  const [missing, setMissing] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<LoadResult | null>(null);
  const [error, setError] = useState("");
  const [values, setValues] = useState<Record<FieldKey, string>>({
    sheetName: defaultTitle,
    title: defaultTitle,
    childOrder: "",
    parentResource: "",
    autoUnlock: "",
    durationInSec: "",
  });

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/loadings/coding-questions");
        const data = await res.json();
        if (cancelled) return;
        setConfigured(Boolean(data.configured));
        setMissing(data.missing || []);
      } catch {
        if (!cancelled) setConfigured(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  if (configured === false) {
    return (
      <span className="text-xs text-muted-foreground" title={missing.join(", ")}>
        Loading not configured
      </span>
    );
  }

  const submit = async () => {
    setLoading(true);
    setError("");
    setResult(null);
    try {
      const res = await fetch(
        `/api/loadings/coding-questions?problemId=${encodeURIComponent(problemId)}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(values),
        },
      );
      const data = await res.json();
      if (!res.ok && !data.batches) throw new Error(data.error || `HTTP ${res.status}`);
      setResult(data as LoadResult);
      if (!data.success && data.error) setError(data.error);
    } catch (e) {
      setError((e as Error).message || "Load failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Button
        size="sm"
        variant={open ? "secondary" : "default"}
        onClick={() => setOpen((v) => !v)}
        className="shrink-0"
      >
        {open ? "Cancel" : "Load to beta"}
      </Button>

      {open && (
        <div className="basis-full mt-3 rounded-md border bg-card p-4">
          <div className="grid gap-3 sm:grid-cols-2">
            {FIELDS.map((field) => (
              <div key={field.key} className="flex flex-col gap-1">
                <Label htmlFor={`load-${field.key}`} className="text-xs">
                  {field.label}
                </Label>
                <Input
                  id={`load-${field.key}`}
                  value={values[field.key]}
                  placeholder={field.hint}
                  disabled={loading}
                  onChange={(e) =>
                    setValues((prev) => ({ ...prev, [field.key]: e.target.value }))
                  }
                />
              </div>
            ))}
          </div>

          <div className="mt-3 flex items-center gap-3">
            <Button size="sm" onClick={submit} disabled={loading}>
              {loading ? "Loading…" : "Run load"}
            </Button>
            <p className="text-xs text-muted-foreground">
              {loading
                ? "Sheet prep → S3 upload → SHEET_LOADING → unlock. This can take several minutes; keep this tab open."
                : "Questions are split across question sets so none exceeds 50."}
            </p>
          </div>

          {error && (
            <p className="mt-3 rounded border border-destructive/40 bg-destructive/10 px-3 py-2 text-xs text-destructive">
              {error}
            </p>
          )}

          {result?.batches?.length ? (
            <ul className="mt-3 space-y-2 text-xs">
              {result.batches.map((batch) => (
                <li key={batch.questionSetId} className="rounded border px-3 py-2">
                  <span className={batch.success ? "text-foreground" : "text-destructive"}>
                    {batch.success ? "✓" : "✕"} {batch.questionCount} question(s) →{" "}
                    {batch.questionSetId} ({batch.loadVia === "sheet" ? "SHEET_LOADING" : "JSON_LOADING"})
                  </span>
                  {(batch.autoFixedDuplicateQuestionIds > 0 ||
                    batch.autoGeneratedMissingQuestionIds > 0) && (
                    <span className="block text-muted-foreground">
                      auto-fixed ids: {batch.autoFixedDuplicateQuestionIds} duplicate,{" "}
                      {batch.autoGeneratedMissingQuestionIds} missing
                    </span>
                  )}
                  <span className="flex gap-3">
                    {batch.sheetUrl && (
                      <a className="underline" href={batch.sheetUrl} target="_blank" rel="noreferrer">
                        Sheet
                      </a>
                    )}
                    {batch.taskOutputUrl && (
                      <a
                        className="underline"
                        href={batch.taskOutputUrl}
                        target="_blank"
                        rel="noreferrer"
                      >
                        Task output
                      </a>
                    )}
                  </span>
                  {batch.error && <span className="block text-destructive">{batch.error}</span>}
                </li>
              ))}
            </ul>
          ) : null}
        </div>
      )}
    </>
  );
}
