#!/usr/bin/env bash
# One-shot local dev setup for Ubuntu / Linux / macOS.
# Usage: ./scripts/setup-local.sh
#
# Pre-fill shared secrets: copy scripts/team-secrets.env.example → scripts/team-secrets.env
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SECRETS_FILE="$ROOT/scripts/team-secrets.env"
VENV_DIR="${HOME}/.codingautomation-venv"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}→${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}!${NC} $*"; }
fail()  { echo -e "${RED}✗${NC} $*" >&2; exit 1; }

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "Missing required command: $1"
  fi
}

version_ge() {
  local want="$1" have="$2"
  [ "$(printf '%s\n%s\n' "$want" "$have" | sort -V | head -n1)" = "$want" ]
}

load_team_secrets() {
  if [ -f "$SECRETS_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$SECRETS_FILE"
    set +a
    ok "Loaded shared secrets from scripts/team-secrets.env"
  else
    warn "No scripts/team-secrets.env found — you'll enter all values manually"
    warn "Tip: cp scripts/team-secrets.env.example scripts/team-secrets.env"
  fi
}

prompt_with_default() {
  local label="$1" default="$2" var_name="$3"
  local input=""
  read -r -p "$label [$default]: " input
  input="${input:-$default}"
  printf -v "$var_name" '%s' "$input"
}

echo ""
echo "========================================"
echo "  Coding Automation — Local Setup"
echo "========================================"
echo ""

info "Checking prerequisites..."

need_cmd git
need_cmd node
need_cmd npm
need_cmd python3

NODE_VER="$(node -v | sed 's/^v//')"
PY_VER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")')"

if ! version_ge "20.0.0" "$NODE_VER"; then
  fail "Node.js 20+ required (found v$NODE_VER). Install: https://nodejs.org/"
fi

if ! python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)'; then
  fail "Python 3.11+ required (found $PY_VER)."
fi

ok "git $(git --version | awk '{print $3}')"
ok "node v$NODE_VER"
ok "npm v$(npm -v)"
ok "python $PY_VER"
echo ""

load_team_secrets
echo ""

DEFAULT_DB="${DATABASE_URL:-postgresql://${USER}@localhost:5432/codingautomation}"
DEFAULT_APP_URL="${APP_URL:-http://localhost:5001}"

info "Configure environment (press Enter to accept defaults in brackets)."
echo ""

prompt_with_default "DATABASE_URL" "$DEFAULT_DB" DATABASE_URL

if [ -z "${OPENROUTER_API_KEY:-}" ]; then
  read -r -s -p "OPENROUTER_API_KEY: " OPENROUTER_API_KEY
  echo ""
  [ -n "$OPENROUTER_API_KEY" ] || fail "OPENROUTER_API_KEY is required"
else
  ok "Using OPENROUTER_API_KEY from team-secrets.env"
fi

if [ -z "${CRON_SECRET:-}" ]; then
  read -r -s -p "CRON_SECRET (leave blank to auto-generate): " CRON_SECRET
  echo ""
  if [ -z "$CRON_SECRET" ]; then
    CRON_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    ok "Generated CRON_SECRET"
  fi
else
  ok "Using CRON_SECRET from team-secrets.env"
fi

if [ -z "${ADMIN_SECRET_KEY:-}" ]; then
  read -r -s -p "ADMIN_SECRET_KEY: " ADMIN_SECRET_KEY
  echo ""
  [ -n "$ADMIN_SECRET_KEY" ] || fail "ADMIN_SECRET_KEY is required"
else
  ok "Using ADMIN_SECRET_KEY from team-secrets.env"
fi

RESEND_API_KEY="${RESEND_API_KEY:-}"
OPENROUTER_BASE_URL="${OPENROUTER_BASE_URL:-}"
prompt_with_default "APP_URL" "$DEFAULT_APP_URL" APP_URL

echo ""

info "Creating Python virtual environment at $VENV_DIR ..."
info "(outside the repo — avoids Turbopack symlink issues during build)"
if [ ! -d "$VENV_DIR" ]; then
  python3 -m venv "$VENV_DIR"
  ok "Created $VENV_DIR"
else
  warn "Reusing existing $VENV_DIR"
fi

VENV_PYTHON="$VENV_DIR/bin/python3"
[ -x "$VENV_PYTHON" ] || fail "Expected venv python at $VENV_PYTHON"

info "Installing Python dependencies..."
"$VENV_PYTHON" -m pip install --upgrade pip --quiet
"$VENV_PYTHON" -m pip install -r pipeline/requirements.txt --quiet
ok "Python packages installed"
echo ""

ENV_FILE="$ROOT/.env.local"
if [ -f "$ENV_FILE" ]; then
  read -r -p ".env.local already exists. Overwrite? (y/N): " OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    fail "Aborted — .env.local was not changed."
  fi
  cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d-%H%M%S)"
  ok "Backed up existing .env.local"
fi

info "Writing .env.local..."
{
  echo "# Generated by scripts/setup-local.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "PIPELINE_ROOT=$ROOT/pipeline"
  echo "PYTHON_PATH=$VENV_PYTHON"
  echo "OPENROUTER_API_KEY=$OPENROUTER_API_KEY"
  echo "ADMIN_SECRET_KEY=$ADMIN_SECRET_KEY"
  echo "DATABASE_URL=$DATABASE_URL"
  echo "CRON_SECRET=$CRON_SECRET"
  if [ -n "$RESEND_API_KEY" ]; then
    echo "RESEND_API_KEY=$RESEND_API_KEY"
  fi
  if [ -n "$OPENROUTER_BASE_URL" ]; then
    echo "OPENROUTER_BASE_URL=$OPENROUTER_BASE_URL"
  fi
  echo "PORT=5001"
  echo "INTERNAL_API_URL=http://127.0.0.1:5001"
  echo "APP_URL=$APP_URL"
  echo "NEXT_PUBLIC_APP_URL=$APP_URL"
  echo ""
  echo "# Local file storage (no Replit bucket needed)"
} > "$ENV_FILE"
ok "Wrote .env.local"
echo ""

info "Installing npm dependencies (this may take a minute)..."
npm install --no-audit --no-fund
ok "npm packages installed"
echo ""

info "Syncing database schema (npm run db:push)..."
npm run db:push
ok "Database schema synced"
echo ""

echo "========================================"
echo -e "${GREEN}Setup complete!${NC}"
echo "========================================"
echo ""
echo "Start the dev server:"
echo "  npm run dev"
echo ""
echo "Then open:"
echo "  http://localhost:5001"
echo ""
echo "Sign up at /signup — admin secret: (see ADMIN_SECRET_KEY in .env.local)"
echo ""
