import test from "node:test";
import assert from "node:assert/strict";
import {
  buildAdminZip,
  LINK_FILE_JSON_LOADING,
  LINK_FILE_SHEET_LOADING,
  dedupeEvaluationMetricsByLanguage,
  parseCodingQuestionsPayload,
  prepareQuestionsForAdminZip,
  stringifyForAdminZip,
} from "./coding-questions-json";

test("parseCodingQuestionsPayload accepts arrays and wrapper keys", () => {
  assert.deepEqual(parseCodingQuestionsPayload([{ a: 1 }]), [{ a: 1 }]);
  assert.deepEqual(parseCodingQuestionsPayload({ coding_questions: [{ a: 1 }] }), [{ a: 1 }]);
  assert.deepEqual(parseCodingQuestionsPayload({ questions: [{ a: 1 }] }), [{ a: 1 }]);
  assert.equal(parseCodingQuestionsPayload({ nope: [] }), null);
  assert.equal(parseCodingQuestionsPayload("x"), null);
});

test("dedupeEvaluationMetricsByLanguage keeps the first entry per language", () => {
  const [row] = dedupeEvaluationMetricsByLanguage([
    {
      test_case_evaluation_metrics: [
        { language: "PYTHON", weight: 1 },
        { language: "python", weight: 2 },
        { language: "JAVA", weight: 3 },
      ],
    },
  ]);
  assert.deepEqual(row.test_case_evaluation_metrics, [
    { language: "PYTHON", weight: 1 },
    { language: "JAVA", weight: 3 },
  ]);
});

test("prepareQuestionsForAdminZip stamps set id and continues ordering", () => {
  const setId = "11111111-1111-4111-8111-111111111111";
  const prepared = prepareQuestionsForAdminZip(
    [{ question_id: "q1" }, { question_id: "q2" }],
    { questionSetId: setId, orderStart: 7 },
  );
  assert.deepEqual(
    prepared.normalized.map((r) => [r.question_id, r.order, r.question_set_id]),
    [
      ["q1", 7, setId],
      ["q2", 8, setId],
    ],
  );
  assert.deepEqual(prepared.questionSetJson, [
    { question_set_id: setId, question_id: "q1", order: 7 },
    { question_set_id: setId, question_id: "q2", order: 8 },
  ]);
});

test("prepareQuestionsForAdminZip repairs missing and duplicate question ids", () => {
  const prepared = prepareQuestionsForAdminZip([{ question_id: "dup" }, { question_id: "dup" }, {}]);
  const ids = prepared.normalized.map((r) => String(r.question_id));
  assert.equal(new Set(ids).size, 3, "ids must be unique");
  assert.equal(prepared.autoFixedDuplicateQuestionIds.length, 1);
  assert.equal(prepared.autoGeneratedMissingQuestionIds.length, 1);
  // The nested question object tracks the final id too.
  const nested = prepareQuestionsForAdminZip([{ question: { id: "old" } }]);
  const q = nested.normalized[0].question as Record<string, unknown>;
  assert.equal(q.id, nested.normalized[0].question_id);
});

test("stringifyForAdminZip writes time_limit_to_execute_in_seconds as a float", () => {
  const out = stringifyForAdminZip([{ time_limit_to_execute_in_seconds: 5 }]);
  assert.match(out, /"time_limit_to_execute_in_seconds": 5\.0/);
  const already = stringifyForAdminZip([{ time_limit_to_execute_in_seconds: 2.5 }]);
  assert.match(already, /"time_limit_to_execute_in_seconds": 2\.5/);
});

test("buildAdminZip produces a zip holding both admin files", async () => {
  const prepared = prepareQuestionsForAdminZip([{ question_id: "q1" }]);
  const zip = await buildAdminZip(prepared);
  assert.equal(zip.subarray(0, 2).toString("ascii"), "PK");
  const text = zip.toString("latin1");
  assert.ok(text.includes("coding_questions.json"));
  assert.ok(text.includes("question_sets_questions.json"));
});

test("buildAdminZip defaults to the plural link file JSON_LOADING requires", async () => {
  // With the singular name the backend links nothing and still reports SUCCESS,
  // so the wrong name is invisible at runtime — pin it here instead.
  const prepared = prepareQuestionsForAdminZip([{ question_id: "q1" }]);
  const jsonZip = (await buildAdminZip(prepared)).toString("latin1");
  assert.equal(LINK_FILE_JSON_LOADING, "question_sets_questions.json");
  assert.ok(jsonZip.includes(LINK_FILE_JSON_LOADING));

  const sheetZip = (await buildAdminZip(prepared, LINK_FILE_SHEET_LOADING)).toString("latin1");
  assert.equal(LINK_FILE_SHEET_LOADING, "question_sets_question.json");
  assert.ok(sheetZip.includes(LINK_FILE_SHEET_LOADING));
});
