/**
 * coding_questions.json -> admin zip (coding_questions.json + question_sets_question.json).
 *
 * Ported from the Loadings app (server.js prepareCodingQuestionsForAdminZip /
 * writeCodingQuestionsAdminZip). Pure except for buildAdminZip, which streams
 * the two JSON files into an in-memory zip.
 */

import { randomUUID } from "crypto";
import { PassThrough } from "stream";
import archiver from "archiver";

export interface CodingQuestionRow {
  [key: string]: unknown;
}

export interface QuestionSetLink {
  question_set_id: string;
  question_id: string;
  order: number;
}

export interface PreparedQuestions {
  normalized: CodingQuestionRow[];
  questionSetJson: QuestionSetLink[];
  questionSetId: string;
  autoFixedDuplicateQuestionIds: { index: number; oldQuestionId: string; newQuestionId: string }[];
  autoGeneratedMissingQuestionIds: { index: number; generatedQuestionId: string }[];
}

/** Accept a bare array or the common wrapper keys the pipeline/composer emit. */
export function parseCodingQuestionsPayload(parsed: unknown): CodingQuestionRow[] | null {
  if (Array.isArray(parsed)) return parsed as CodingQuestionRow[];
  if (parsed && typeof parsed === "object") {
    const obj = parsed as Record<string, unknown>;
    const nested =
      obj.coding_questions ?? obj.codingQuestions ?? obj.questions ?? obj.data ?? obj.items;
    return Array.isArray(nested) ? (nested as CodingQuestionRow[]) : null;
  }
  return null;
}

/** Backend rejects duplicate languages in test_case_evaluation_metrics; keep the first per language. */
export function dedupeEvaluationMetricsByLanguage(rows: CodingQuestionRow[]): CodingQuestionRow[] {
  return rows.map((row) => {
    if (!row || typeof row !== "object") return row;
    const next = { ...row };
    const metrics = next.test_case_evaluation_metrics;
    if (!Array.isArray(metrics) || metrics.length === 0) return next;
    const seen = new Set<string>();
    next.test_case_evaluation_metrics = metrics.filter((m) => {
      if (!m || typeof m !== "object") return true;
      const entry = m as Record<string, unknown>;
      const lang = String(entry.language ?? entry.lang ?? "").trim().toUpperCase();
      if (!lang) return true;
      if (seen.has(lang)) return false;
      seen.add(lang);
      return true;
    });
    return next;
  });
}

function readQuestionId(item: CodingQuestionRow): string {
  if (!item || typeof item !== "object") return "";
  const nested = item.question as Record<string, unknown> | undefined;
  const raw =
    item.question_id ??
    item.questionId ??
    item.qid ??
    item.id ??
    (nested && (nested.id ?? nested.question_id ?? nested.questionId));
  return raw != null ? String(raw).trim() : "";
}

/**
 * Stamp question_set_id / question_id / order onto every row and derive the
 * question_sets_question.json link rows.
 */
export function prepareQuestionsForAdminZip(
  parsedList: CodingQuestionRow[],
  options: { questionSetId?: string; orderStart?: number } = {},
): PreparedQuestions {
  const orderStart = Math.max(1, parseInt(String(options.orderStart ?? 1), 10) || 1);
  const questionSetId = String(options.questionSetId || "").trim() || randomUUID();
  const seen = new Set<string>();
  const autoFixedDuplicateQuestionIds: PreparedQuestions["autoFixedDuplicateQuestionIds"] = [];
  const autoGeneratedMissingQuestionIds: PreparedQuestions["autoGeneratedMissingQuestionIds"] = [];

  const normalized = dedupeEvaluationMetricsByLanguage(parsedList).map((item, idx) => {
    const qid = readQuestionId(item);
    let finalQid = qid;
    if (!finalQid) {
      finalQid = randomUUID();
      autoGeneratedMissingQuestionIds.push({ index: idx, generatedQuestionId: finalQid });
    }
    if (seen.has(finalQid)) {
      const newQid = randomUUID();
      autoFixedDuplicateQuestionIds.push({
        index: idx,
        oldQuestionId: qid || "(auto-generated duplicate)",
        newQuestionId: newQid,
      });
      finalQid = newQid;
    }
    seen.add(finalQid);

    const row: CodingQuestionRow = {
      ...item,
      question_set_id: questionSetId,
      question_id: finalQid,
      id: finalQid,
      order: orderStart + idx,
    };
    if (row.question && typeof row.question === "object") {
      const nested = row.question as Record<string, unknown>;
      nested.id = finalQid;
      nested.question_id = finalQid;
    }
    return row;
  });

  const questionSetJson = normalized.map((row) => ({
    question_set_id: questionSetId,
    question_id: String(row.question_id),
    order: Number(row.order),
  }));

  return {
    normalized,
    questionSetJson,
    questionSetId,
    autoFixedDuplicateQuestionIds,
    autoGeneratedMissingQuestionIds,
  };
}

/** The backend wants a float here, and JSON.stringify writes 5 for 5.0. */
export function stringifyForAdminZip(rows: CodingQuestionRow[]): string {
  return JSON.stringify(rows, null, 2).replace(
    /"time_limit_to_execute_in_seconds"\s*:\s*(-?\d+)(?=\s*[,}\]])/g,
    (_, intPart: string) => `"time_limit_to_execute_in_seconds": ${intPart}.0`,
  );
}

/**
 * Name of the question-set link file inside the admin zip. The two backend task
 * types disagree: JSON_LOADING reads `question_sets_questions.json` (plural) and,
 * if it is absent, links nothing while still reporting SUCCESS; the new-unit
 * SHEET_LOADING zip uses the singular name the Loadings app writes.
 */
export const LINK_FILE_JSON_LOADING = "question_sets_questions.json";
export const LINK_FILE_SHEET_LOADING = "question_sets_question.json";

/** Build the two-file admin zip entirely in memory. */
export async function buildAdminZip(
  prepared: PreparedQuestions,
  linkFileName: string = LINK_FILE_JSON_LOADING,
): Promise<Buffer> {
  const archive = archiver("zip", { zlib: { level: 9 } });
  const sink = new PassThrough();
  const chunks: Buffer[] = [];
  sink.on("data", (c: Buffer) => chunks.push(c));

  const done = new Promise<void>((resolve, reject) => {
    sink.on("end", resolve);
    sink.on("error", reject);
    archive.on("error", reject);
  });

  archive.pipe(sink);
  archive.append(stringifyForAdminZip(prepared.normalized), { name: "coding_questions.json" });
  archive.append(JSON.stringify(prepared.questionSetJson, null, 2), { name: linkFileName });
  await archive.finalize();
  await done;

  return Buffer.concat(chunks);
}
