/**
 * Load a coding_questions.json into NKB beta.
 *
 * Per question set the flow is:
 *   empty set  -> copy the sheet template, fill it, SHEET_LOADING, then unlock
 *   used set   -> JSON_LOADING with load_data_type QUESTION_SET (no sheet)
 *
 * A batch bigger than the room left in a set is split across sets, so no set
 * ever passes the 50-question cap.
 *
 * There is no operator configuration: the question set, the unit title, its
 * child order and its parent all come from the planner, and auto-unlock is
 * fixed by the design spec. The caller supplies only the questions.
 */

import { randomUUID } from "crypto";
import { CODING_QUESTIONS_TEMPLATE_URL, missingLoadingsConfig } from "./config";
import {
  buildAdminZip,
  prepareQuestionsForAdminZip,
  LINK_FILE_JSON_LOADING,
  LINK_FILE_SHEET_LOADING,
  type CodingQuestionRow,
} from "./coding-questions-json";
import {
  batchUpdateCells,
  clearValues,
  copySpreadsheet,
  shareSpreadsheet,
  spreadsheetIdFromUrl,
  type CellUpdate,
} from "./google-sheets";
import { runNkbTask, uploadZipToS3 } from "./nkb";
import {
  planQuestionSetBatches,
  registryUpsertForBatch,
  upsertRegistryRow,
  type LoadBatch,
} from "./practice-set-db";
import { lookupQuestionSetQuestions } from "./question-set";

const SHEET_LOADING_POLL = { maxAttempts: 100, pollMs: 3000 };
const UNLOCK_POLL = { maxAttempts: 60, pollMs: 3000 };

export interface BatchResult {
  questionSetId: string;
  questionCount: number;
  orderStart: number;
  loadVia: "sheet" | "json";
  isNewSet: boolean;
  questionIds: string[];
  uploadedZipUrl: string;
  sheetUrl?: string;
  commonUnitId?: string;
  taskOutputUrl?: string;
  success: boolean;
  error?: string;
  autoFixedDuplicateQuestionIds: number;
  autoGeneratedMissingQuestionIds: number;
}

export interface LoadResult {
  success: boolean;
  batches: BatchResult[];
  questionCount: number;
  error?: string;
}

/**
 * A finished NKB task does not mean the content landed: the task only spawns an
 * ECS worker, and observed runs returned SUCCESS while linking nothing. So a
 * batch counts as loaded only once the questions show up in the set.
 */
async function confirmLinked(
  questionSetId: string,
  questionIds: string[],
  attempts = 3,
  waitMs = 10_000,
): Promise<{ linked: boolean; missing: string[] }> {
  const wanted = questionIds.map((id) => id.toLowerCase());
  let missing = wanted;

  for (let attempt = 0; attempt < attempts; attempt++) {
    if (attempt > 0) await new Promise((r) => setTimeout(r, waitMs));
    try {
      const lookup = await lookupQuestionSetQuestions(questionSetId);
      const present = new Set(lookup.questionIds.map((id) => id.toLowerCase()));
      missing = wanted.filter((id) => !present.has(id));
      if (!missing.length) return { linked: true, missing: [] };
    } catch (err) {
      console.warn("[Loadings] link verification failed:", (err as Error).message);
    }
  }
  return { linked: false, missing };
}

/** Testing content is always unlocked on load — design spec §3 step 2. */
const AUTO_UNLOCK = "TRUE";

function pushCell(updates: CellUpdate[], range: string, value?: string): void {
  if (value == null || String(value).trim() === "") return;
  updates.push({ range, values: [[String(value).trim()]] });
}

/**
 * Cells the loading sheet needs. Every value is derived — the question set id
 * and unit identity come from the planner, auto-unlock is fixed by the spec —
 * so no operator input reaches a sheet cell.
 *
 * `ResourcesData!G3`/`H3` place the unit in the real beta course tree, so they
 * are written ONLY for a unit this run minted, and then with the very parent
 * `createNextTestingUnit` derived the child order against. A set that already
 * exists is already placed at an order nothing here computed; writing those
 * cells would move it.
 *
 * ponytail: a non-minted set on the sheet path (a registry row whose questions
 * were later deleted) therefore gets no title and no placement — its unit
 * normally already exists in beta. If that ever stops holding, carry the
 * registry row's `unitName` onto the batch rather than reintroducing a form.
 */
export function buildSheetCellUpdates(args: {
  questionSetId: string;
  unitId: string;
  batch: Pick<LoadBatch, "unitTitle" | "childOrder" | "parentResource">;
}): CellUpdate[] {
  const { questionSetId, unitId, batch } = args;
  const updates: CellUpdate[] = [];
  pushCell(updates, "ResourcesData!A2", questionSetId);
  if (batch.childOrder != null) {
    if (!batch.parentResource) {
      throw new Error(
        "NKB_TESTING_PARENT_RESOURCE is not set, so the parent of the new testing unit is unknown — refusing to create it unparented.",
      );
    }
    pushCell(updates, "ResourcesData!G3", String(batch.childOrder));
    pushCell(updates, "ResourcesData!H3", batch.parentResource);
  }
  pushCell(updates, "ResourcesData!I2", AUTO_UNLOCK);
  pushCell(updates, "Units!A2", questionSetId);
  pushCell(updates, "Units!B2", unitId);
  pushCell(updates, "QuestionSet!A2", questionSetId);
  pushCell(updates, "QuestionSet!B2", batch.unitTitle);
  return updates;
}

/**
 * Google Drive name for the copied loading sheet — also sent as
 * `spread_sheet_name`. Derived, not typed: the unit title says which unit it
 * belongs to and the timestamp keeps repeat loads apart in the Drive list.
 */
export function deriveSheetName(
  batch: Pick<LoadBatch, "questionSetId" | "unitTitle">,
  now: Date = new Date(),
): string {
  const label = batch.unitTitle?.trim() || `Question set ${batch.questionSetId}`;
  return `${label} ${now.toISOString().slice(0, 19).replace("T", " ")}`;
}

async function prepareSheet(
  batch: LoadBatch,
  unitId: string,
  sheetName: string,
): Promise<string> {
  const templateId = spreadsheetIdFromUrl(CODING_QUESTIONS_TEMPLATE_URL);
  if (!templateId) {
    throw new Error("CODING_QUESTIONS_LOADING_SHEET_URL is not a valid spreadsheet URL.");
  }
  const { spreadsheetId, url } = await copySpreadsheet(templateId, sheetName);
  await shareSpreadsheet(spreadsheetId);
  await batchUpdateCells(
    spreadsheetId,
    buildSheetCellUpdates({ questionSetId: batch.questionSetId, unitId, batch }),
  );
  // The template ships with a stray second title row that breaks the load.
  await clearValues(spreadsheetId, "QuestionSet!B3").catch((err) =>
    console.warn("[Loadings] could not clear QuestionSet!B3:", (err as Error).message),
  );
  return url;
}

async function runBatch(
  batch: LoadBatch,
  questions: CodingQuestionRow[],
  onLog: (phase: string, message: string) => void,
): Promise<BatchResult> {
  const slice = questions.slice(batch.startIndex, batch.startIndex + batch.count);
  const prepared = prepareQuestionsForAdminZip(slice, {
    questionSetId: batch.questionSetId,
    orderStart: batch.orderStart,
  });
  onLog(
    "zip",
    `set ${batch.questionSetId}: packing ${slice.length} question(s) starting at order ${batch.orderStart}`,
  );
  const zip = await buildAdminZip(
    prepared,
    batch.loadVia === "json" ? LINK_FILE_JSON_LOADING : LINK_FILE_SHEET_LOADING,
  );
  onLog("upload", `set ${batch.questionSetId}: uploading zip`);
  const uploadedZipUrl = await uploadZipToS3(zip);

  const result: BatchResult = {
    questionSetId: batch.questionSetId,
    questionCount: slice.length,
    orderStart: batch.orderStart,
    loadVia: batch.loadVia,
    isNewSet: batch.isNewSet,
    questionIds: prepared.normalized.map((r) => String(r.question_id)),
    uploadedZipUrl,
    success: false,
    autoFixedDuplicateQuestionIds: prepared.autoFixedDuplicateQuestionIds.length,
    autoGeneratedMissingQuestionIds: prepared.autoGeneratedMissingQuestionIds.length,
  };

  if (batch.loadVia === "json") {
    onLog("task", `set ${batch.questionSetId}: running JSON_LOADING`);
    const load = await runNkbTask(
      "JSON_LOADING",
      { load_data_type: "QUESTION_SET", input_dir_path_url: uploadedZipUrl },
      SHEET_LOADING_POLL,
    );
    result.taskOutputUrl = load.taskOutputUrl;
    if (!load.success) {
      result.error = load.error;
      return result;
    }
    onLog(
      "verify",
      `set ${batch.questionSetId}: confirming ${result.questionIds.length} question(s) linked`,
    );
    const check = await confirmLinked(batch.questionSetId, result.questionIds);
    result.success = check.linked;
    if (!check.linked) {
      result.error = `JSON_LOADING reported ${load.status} but ${check.missing.length} question(s) are not linked in the set — the backend accepted the task without loading it.`;
    }
    return result;
  }

  // The unit's whole identity — title, child order, parent, common unit id —
  // comes from the planner. There is nothing for an operator to supply.
  const unitId = batch.commonUnitId?.trim() || randomUUID();
  const sheetName = deriveSheetName(batch);
  result.commonUnitId = unitId;
  result.sheetUrl = await prepareSheet(batch, unitId, sheetName);

  onLog("task", `set ${batch.questionSetId}: running SHEET_LOADING`);
  const load = await runNkbTask(
    "SHEET_LOADING",
    {
      spread_sheet_name: sheetName,
      data_sets_to_be_loaded: ["ResourcesData", "Units", "QuestionSet"],
      question_set_questions_dir_path_url: uploadedZipUrl,
    },
    SHEET_LOADING_POLL,
  );
  result.taskOutputUrl = load.taskOutputUrl;
  if (!load.success) {
    result.error = load.error;
    return result;
  }

  onLog("unlock", `set ${batch.questionSetId}: unlocking for users`);
  const unlock = await runNkbTask(
    "UNLOCK_RESOURCES_FOR_USERS",
    { resource_ids: [batch.questionSetId] },
    UNLOCK_POLL,
  );
  if (!unlock.success) {
    result.error = `${unlock.error} (sheet load succeeded)`;
    return result;
  }

  onLog(
    "verify",
    `set ${batch.questionSetId}: confirming ${result.questionIds.length} question(s) linked`,
  );
  const check = await confirmLinked(batch.questionSetId, result.questionIds);
  result.success = check.linked;
  if (!check.linked) {
    result.error = `SHEET_LOADING and unlock reported success but ${check.missing.length} question(s) are not linked in the set — the backend accepted the task without loading it.`;
  }
  return result;
}

export async function loadCodingQuestions(
  questions: CodingQuestionRow[],
  opts: { onLog?: (phase: string, message: string) => void } = {},
): Promise<LoadResult> {
  // A throwing onLog (e.g. a DB write in the caller) must never fail an
  // otherwise-successful load — swallow it once here, for every call site.
  const rawOnLog = opts.onLog ?? (() => {});
  const onLog = (phase: string, message: string): void => {
    try {
      rawOnLog(phase, message);
    } catch (err) {
      console.warn("[Loadings] onLog failed:", (err as Error).message);
    }
  };

  const missing = missingLoadingsConfig();
  onLog("config", missing.length ? `missing: ${missing.join(", ")}` : "loading is configured");
  if (missing.length) {
    return {
      success: false,
      batches: [],
      questionCount: questions.length,
      error: `Loading is not configured. Missing: ${missing.join(", ")}`,
    };
  }

  onLog("plan", `planning batches for ${questions.length} question(s)`);
  const { batches } = await planQuestionSetBatches(questions.length, onLog);
  onLog("plan", `${batches.length} batch(es) across question sets`);
  const results: BatchResult[] = [];

  for (let i = 0; i < batches.length; i++) {
    const result = await runBatch(batches[i], questions, onLog);
    results.push(result);
    if (result.success) {
      // Only a rollover-minted set is recorded, under its derived
      // "Coding Testing N" title — renaming an existing row would break the
      // next rollover's count.
      const upsert = registryUpsertForBatch(batches[i]);
      if (upsert) {
        await upsertRegistryRow(upsert.questionSetId, upsert.unitName).catch((err) =>
          console.warn("[Loadings] registry upsert failed:", (err as Error).message),
        );
      }
    } else {
      // Stop before loading later batches into other sets — the operator needs
      // to see the failure while the remaining questions are still unloaded.
      break;
    }
  }

  return {
    success: results.length > 0 && results.every((r) => r.success),
    batches: results,
    questionCount: questions.length,
    error: results.find((r) => !r.success)?.error,
  };
}
