/**
 * Load a coding_questions.json into NKB beta.
 *
 * Per question set the flow is:
 *   empty set  -> copy the sheet template, fill it, SHEET_LOADING, then unlock
 *   used set   -> JSON_LOADING with load_data_type QUESTION_SET (no sheet)
 *
 * A batch bigger than the room left in a set is split across sets, so no set
 * ever passes the 50-question cap.
 */

import { randomUUID } from "crypto";
import { CODING_QUESTIONS_TEMPLATE_URL, missingLoadingsConfig } from "./config";
import {
  buildAdminZip,
  prepareQuestionsForAdminZip,
  LINK_FILE_JSON_LOADING,
  LINK_FILE_SHEET_LOADING,
  type CodingQuestionRow,
} from "./coding-questions-json";
import {
  batchUpdateCells,
  clearValues,
  copySpreadsheet,
  shareSpreadsheet,
  spreadsheetIdFromUrl,
  type CellUpdate,
} from "./google-sheets";
import { runNkbTask, uploadZipToS3 } from "./nkb";
import { planQuestionSetBatches, upsertRegistryRow, type LoadBatch } from "./practice-set-db";
import { lookupQuestionSetQuestions } from "./question-set";

const SHEET_LOADING_POLL = { maxAttempts: 100, pollMs: 3000 };
const UNLOCK_POLL = { maxAttempts: 60, pollMs: 3000 };

export interface LoadForm {
  /** Name for the copied sheet, also sent as spread_sheet_name. */
  sheetName: string;
  /** ResourcesData G3 */
  childOrder: string;
  /** ResourcesData H3 */
  parentResource: string;
  /** ResourcesData I2 */
  autoUnlock: string;
  /** QuestionSet B2 */
  title: string;
  /** Units B2 — generated when omitted. */
  commonUnitId?: string;
  /** Units D2 — seconds, or "MM:SS". */
  durationInSec?: string;
}

export interface BatchResult {
  questionSetId: string;
  questionCount: number;
  orderStart: number;
  loadVia: "sheet" | "json";
  isNewSet: boolean;
  questionIds: string[];
  uploadedZipUrl: string;
  sheetUrl?: string;
  commonUnitId?: string;
  taskOutputUrl?: string;
  success: boolean;
  error?: string;
  autoFixedDuplicateQuestionIds: number;
  autoGeneratedMissingQuestionIds: number;
}

export interface LoadResult {
  success: boolean;
  batches: BatchResult[];
  questionCount: number;
  error?: string;
}

/**
 * A finished NKB task does not mean the content landed: the task only spawns an
 * ECS worker, and observed runs returned SUCCESS while linking nothing. So a
 * batch counts as loaded only once the questions show up in the set.
 */
async function confirmLinked(
  questionSetId: string,
  questionIds: string[],
  attempts = 3,
  waitMs = 10_000,
): Promise<{ linked: boolean; missing: string[] }> {
  const wanted = questionIds.map((id) => id.toLowerCase());
  let missing = wanted;

  for (let attempt = 0; attempt < attempts; attempt++) {
    if (attempt > 0) await new Promise((r) => setTimeout(r, waitMs));
    try {
      const lookup = await lookupQuestionSetQuestions(questionSetId);
      const present = new Set(lookup.questionIds.map((id) => id.toLowerCase()));
      missing = wanted.filter((id) => !present.has(id));
      if (!missing.length) return { linked: true, missing: [] };
    } catch (err) {
      console.warn("[Loadings] link verification failed:", (err as Error).message);
    }
  }
  return { linked: false, missing };
}

/** "47:01" is entered as a formula so the sheet stores seconds. */
function durationToSheetValue(val?: string): string {
  const s = String(val ?? "").trim();
  if (!s) return "";
  const match = s.match(/^\s*(\d+)\s*:\s*(\d+)\s*(?:Min|min|m)?\s*$/i);
  if (match) return `=${match[1]}*60+${match[2]}`;
  return s;
}

function pushCell(updates: CellUpdate[], range: string, value?: string): void {
  if (value == null || String(value).trim() === "") return;
  updates.push({ range, values: [[String(value).trim()]] });
}

export function buildSheetCellUpdates(args: {
  questionSetId: string;
  unitId: string;
  form: LoadForm;
}): CellUpdate[] {
  const { questionSetId, unitId, form } = args;
  const updates: CellUpdate[] = [];
  pushCell(updates, "ResourcesData!A2", questionSetId);
  pushCell(updates, "ResourcesData!G3", form.childOrder);
  pushCell(updates, "ResourcesData!H3", form.parentResource);
  pushCell(updates, "ResourcesData!I2", form.autoUnlock);
  pushCell(updates, "Units!A2", questionSetId);
  pushCell(updates, "Units!B2", unitId);
  const duration = durationToSheetValue(form.durationInSec);
  if (duration) updates.push({ range: "Units!D2", values: [[duration]] });
  pushCell(updates, "QuestionSet!A2", questionSetId);
  pushCell(updates, "QuestionSet!B2", form.title);
  return updates;
}

async function prepareSheet(
  questionSetId: string,
  unitId: string,
  form: LoadForm,
  sheetName: string,
): Promise<string> {
  const templateId = spreadsheetIdFromUrl(CODING_QUESTIONS_TEMPLATE_URL);
  if (!templateId) {
    throw new Error("CODING_QUESTIONS_LOADING_SHEET_URL is not a valid spreadsheet URL.");
  }
  const { spreadsheetId, url } = await copySpreadsheet(templateId, sheetName);
  await shareSpreadsheet(spreadsheetId);
  await batchUpdateCells(spreadsheetId, buildSheetCellUpdates({ questionSetId, unitId, form }));
  // The template ships with a stray second title row that breaks the load.
  await clearValues(spreadsheetId, "QuestionSet!B3").catch((err) =>
    console.warn("[Loadings] could not clear QuestionSet!B3:", (err as Error).message),
  );
  return url;
}

async function runBatch(
  batch: LoadBatch,
  questions: CodingQuestionRow[],
  form: LoadForm,
  batchIndex: number,
  batchTotal: number,
): Promise<BatchResult> {
  const slice = questions.slice(batch.startIndex, batch.startIndex + batch.count);
  const prepared = prepareQuestionsForAdminZip(slice, {
    questionSetId: batch.questionSetId,
    orderStart: batch.orderStart,
  });
  const zip = await buildAdminZip(
    prepared,
    batch.loadVia === "json" ? LINK_FILE_JSON_LOADING : LINK_FILE_SHEET_LOADING,
  );
  const uploadedZipUrl = await uploadZipToS3(zip);

  const result: BatchResult = {
    questionSetId: batch.questionSetId,
    questionCount: slice.length,
    orderStart: batch.orderStart,
    loadVia: batch.loadVia,
    isNewSet: batch.isNewSet,
    questionIds: prepared.normalized.map((r) => String(r.question_id)),
    uploadedZipUrl,
    success: false,
    autoFixedDuplicateQuestionIds: prepared.autoFixedDuplicateQuestionIds.length,
    autoGeneratedMissingQuestionIds: prepared.autoGeneratedMissingQuestionIds.length,
  };

  if (batch.loadVia === "json") {
    const load = await runNkbTask(
      "JSON_LOADING",
      { load_data_type: "QUESTION_SET", input_dir_path_url: uploadedZipUrl },
      SHEET_LOADING_POLL,
    );
    result.taskOutputUrl = load.taskOutputUrl;
    if (!load.success) {
      result.error = load.error;
      return result;
    }
    const check = await confirmLinked(batch.questionSetId, result.questionIds);
    result.success = check.linked;
    if (!check.linked) {
      result.error = `JSON_LOADING reported ${load.status} but ${check.missing.length} question(s) are not linked in the set — the backend accepted the task without loading it.`;
    }
    return result;
  }

  const unitId = form.commonUnitId?.trim() || randomUUID();
  const sheetName = batchTotal > 1 ? `${form.sheetName} (${batchIndex + 1})` : form.sheetName;
  result.commonUnitId = unitId;
  result.sheetUrl = await prepareSheet(batch.questionSetId, unitId, form, sheetName);

  const load = await runNkbTask(
    "SHEET_LOADING",
    {
      spread_sheet_name: sheetName,
      data_sets_to_be_loaded: ["ResourcesData", "Units", "QuestionSet"],
      question_set_questions_dir_path_url: uploadedZipUrl,
    },
    SHEET_LOADING_POLL,
  );
  result.taskOutputUrl = load.taskOutputUrl;
  if (!load.success) {
    result.error = load.error;
    return result;
  }

  const unlock = await runNkbTask(
    "UNLOCK_RESOURCES_FOR_USERS",
    { resource_ids: [batch.questionSetId] },
    UNLOCK_POLL,
  );
  if (!unlock.success) {
    result.error = `${unlock.error} (sheet load succeeded)`;
    return result;
  }

  const check = await confirmLinked(batch.questionSetId, result.questionIds);
  result.success = check.linked;
  if (!check.linked) {
    result.error = `SHEET_LOADING and unlock reported success but ${check.missing.length} question(s) are not linked in the set — the backend accepted the task without loading it.`;
  }
  return result;
}

export async function loadCodingQuestions(
  questions: CodingQuestionRow[],
  form: LoadForm,
): Promise<LoadResult> {
  const missing = missingLoadingsConfig();
  if (missing.length) {
    return {
      success: false,
      batches: [],
      questionCount: questions.length,
      error: `Loading is not configured. Missing: ${missing.join(", ")}`,
    };
  }

  const { batches } = await planQuestionSetBatches(questions.length, form.title);
  const results: BatchResult[] = [];

  for (let i = 0; i < batches.length; i++) {
    const result = await runBatch(batches[i], questions, form, i, batches.length);
    results.push(result);
    if (result.success) {
      await upsertRegistryRow(result.questionSetId, form.title).catch((err) =>
        console.warn("[Loadings] registry upsert failed:", (err as Error).message),
      );
    } else {
      // Stop before loading later batches into other sets — the operator needs
      // to see the failure while the remaining questions are still unloaded.
      break;
    }
  }

  return {
    success: results.length > 0 && results.every((r) => r.success),
    batches: results,
    questionCount: questions.length,
    error: results.find((r) => !r.success)?.error,
  };
}
